// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOgmrG1kp2Yd3E2OuUIgD7DhTlQ_b21kw',
    appId: '1:764109092494:web:447a19473fc072be2f7bdf',
    messagingSenderId: '764109092494',
    projectId: 'app-zalo-6c0f6',
    authDomain: 'app-zalo-6c0f6.firebaseapp.com',
    databaseURL:
        'https://app-zalo-6c0f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-zalo-6c0f6.firebasestorage.app',
    measurementId: 'G-GVT291NYWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTsi-yCLieZvjt8AgR9tsD9ipWULdkr18',
    appId: '1:764109092494:android:ca511bee2fba64412f7bdf',
    messagingSenderId: '764109092494',
    projectId: 'app-zalo-6c0f6',
    databaseURL:
        'https://app-zalo-6c0f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-zalo-6c0f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVcOFb9Ft-jsmohMlqUEVMxdSgt3pr1RA',
    appId: '1:764109092494:ios:dcc0e977bd4d56602f7bdf',
    messagingSenderId: '764109092494',
    projectId: 'app-zalo-6c0f6',
    databaseURL:
        'https://app-zalo-6c0f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-zalo-6c0f6.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVcOFb9Ft-jsmohMlqUEVMxdSgt3pr1RA',
    appId: '1:764109092494:ios:dcc0e977bd4d56602f7bdf',
    messagingSenderId: '764109092494',
    projectId: 'app-zalo-6c0f6',
    databaseURL:
        'https://app-zalo-6c0f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-zalo-6c0f6.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtsBTIL0JNZGHxbXiqQiYkuGCr6ZmbrSc',
    appId: '1:764109092494:web:9f830130514da4a12f7bdf',
    messagingSenderId: '764109092494',
    projectId: 'app-zalo-6c0f6',
    authDomain: 'app-zalo-6c0f6.firebaseapp.com',
    databaseURL:
        'https://app-zalo-6c0f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-zalo-6c0f6.firebasestorage.app',
    measurementId: 'G-V7X1YPGFMF',
  );
}
